### ISSUE TITLE
support intents

### ISSUE THREAD

**Issue by forivall** [brave-warrior/TravisClient-Android#2]

**Comment by forivall** [comment]
ugh, gitskarios lost my message. https://github.com/sahan/Travis-Jr supports this, but it no longer works.

**Comment by brave-warrior** [comment]
Could you please provide better description? Which kind of Intents support do you expect?

**Comment by forivall** [comment]
yeah, sorry about that, I was on my phone.

Basically, when I tap "view build" in google inbox, I get the option to open it in a web browser or in travis jr, since travis jr has registered itself to open urls at "travis-ci.org"

I believe this is where it registers itself: https://github.com/sahan/Travis-Jr/blob/1d0c83b1857a5080ebf0f7d51dbd94ba8fcbdb69/travisjr/AndroidManifest.xml#L55

**Comment by alorma** [comment]
Hey hey hey!

Gitskarios dev here.

I was planning to do a new Travis app, but just saw that one.

If the developer adds intent-filter support, it will be awesome!
